{ config, lib, pkgs, ... }:

let
  cfg = config.programs.codecorral;

  workspaceType = lib.types.submodule {
    options = {
      path = lib.mkOption {
        type = lib.types.str;
        description = "Absolute path to the workspace directory";
      };

      workflows = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        description = "List of workflow definitions to enable for this workspace";
      };

      agentDeck = lib.mkOption {
        type = lib.types.submodule {
          options.profile = lib.mkOption {
            type = lib.types.nullOr lib.types.str;
            default = null;
            description = "Agent-deck profile name for session management";
          };
        };
        default = { };
        description = "Agent-deck configuration for this workspace";
      };

      claudeCode = lib.mkOption {
        type = lib.types.submodule {
          options = {
            model = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Default Claude model for agents";
            };
          };
        };
        default = { };
        description = "Claude Code configuration for this workspace";
      };

      openspec = lib.mkOption {
        type = lib.types.submodule {
          options = {
            schemas = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
              description = "List of OpenSpec schema references to install";
            };
            schemasPath = lib.mkOption {
              type = lib.types.nullOr lib.types.str;
              default = null;
              description = "Relative path to project-local schemas";
            };
            config = lib.mkOption {
              type = lib.types.attrsOf lib.types.anything;
              default = { };
              description = "OpenSpec config overrides";
            };
          };
        };
        default = { };
        description = "OpenSpec configuration for this workspace";
      };
    };
  };

  # Collect all agent-deck profile names to check for duplicates
  agentDeckProfiles = lib.filter (p: p != null)
    (lib.mapAttrsToList (_: ws: ws.agentDeck.profile) cfg.workspaces);

  # Collect all schema lists from all workspaces (union)
  allSchemas = lib.unique (lib.concatMap (ws: ws.openspec.schemas)
    (lib.attrValues cfg.workspaces));

  # Generate config.yaml content
  configContent = let
    workspaceEntries = lib.mapAttrs (name: ws: {
      path = ws.path;
      workflows = ws.workflows;
    } // lib.optionalAttrs (ws.agentDeck.profile != null) {
      agentDeckProfile = ws.agentDeck.profile;
    } // lib.optionalAttrs (ws.claudeCode.model != null) {
      claudeCodeProfile = name;
    }) cfg.workspaces;
  in
    builtins.toJSON { workspaces = workspaceEntries; };
in
{
  meta.maintainers = [ ];

  options.programs.codecorral = {
    enable = lib.mkEnableOption "CodeCorral workflow engine";

    workspaces = lib.mkOption {
      type = lib.types.attrsOf workspaceType;
      default = { };
      description = "Workspace configurations for CodeCorral";
    };
  };

  config = lib.mkIf cfg.enable {
    # Assert no duplicate agent-deck profile names
    assertions = [
      {
        assertion = (lib.length agentDeckProfiles) == (lib.length (lib.unique agentDeckProfiles));
        message = "Duplicate agentDeck profile names across CodeCorral workspaces: ${builtins.toJSON agentDeckProfiles}";
      }
    ];

    # Generate ~/.codecorral/config.yaml
    home.file.".codecorral/config.yaml".text =
      let
        yamlWorkspaces = lib.mapAttrs (name: ws:
          { inherit (ws) path workflows; }
          // lib.optionalAttrs (ws.agentDeck.profile != null) {
            agentDeckProfile = ws.agentDeck.profile;
          }
          // lib.optionalAttrs (ws.claudeCode.model != null) {
            claudeCodeProfile = name;
          }
        ) cfg.workspaces;
      in
        ''
          # Generated by CodeCorral Home Manager module — do not edit manually.
          # Project-level overrides go in .codecorral/config.yaml within each project.
          ${builtins.toJSON { workspaces = yamlWorkspaces; }}
        '';

    # Delegate to upstream agent-deck module if available
    programs.agent-deck = lib.mkIf (config ? programs && config.programs ? agent-deck) (
      let
        profileConfigs = lib.filterAttrs (_: v: v != null)
          (lib.mapAttrs (_: ws: ws.agentDeck.profile) cfg.workspaces);
      in
      {
        profiles = lib.mapAttrs' (_: profileName: {
          name = profileName;
          value = {
            claude.configDir = ".claude-${profileName}";
          };
        }) profileConfigs;
      }
    );

    # Delegate to upstream claude-code module if available
    programs.claude-code = lib.mkIf (config ? programs && config.programs ? claude-code) (
      let
        claudeConfigs = lib.filterAttrs (_: ws: ws.claudeCode.model != null)
          cfg.workspaces;
      in
      {
        profiles = lib.mapAttrs (name: ws: {
          configDir = ".claude-${name}";
          settings = lib.optionalAttrs (ws.claudeCode.model != null) {
            model = ws.claudeCode.model;
          };
        }) claudeConfigs;
      }
    );

    # Delegate to upstream openspec module if available
    programs.openspec = lib.mkIf (config ? programs && config.programs ? openspec) {
      enable = true;
      schemas = allSchemas;
    };
  };
}
